# Numpy Tutorial

numpy は 行列演算などの数値演算用ライブラリです. C実装になっているため, 高速に動作するので 
pythonで数値演算を利用するなら習得必須のライブラリになります. 

早速, Numpyの使い方に慣れてみよう. 

In [19]:
import numpy as np

a = np.arange(6)
a

print a.ndim, a.shape

1 (6,)


reshapeを利用することで, 様々な形の行列を用意できます. 

基本は参照コピーなので. 
ディープコピー(実体のコピー)をするには copy関数を使ってください.

In [11]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
b = a.reshape(2,3)

b[0, 0] =22
b

array([[22,  1,  2],
       [ 3,  4,  5]])

In [14]:
a

array([22,  1,  2,  3,  4,  5])

In [29]:
# 分からないときはhelpを引きましょう
a.reshape?

## Indexing

numpyでは fancy indexing といって, 様々なインデクシングが標準で用意されています.
なれると非常に便利なので, どんどん覚えていきましょう.
ここで紹介される例は, ほんの一例なので 詳しくはnumpyの[indexing](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)を参照してください

In [31]:
a[[2,3,4]]

array([2, 3, 4])

In [34]:
a > 4 # boolean 配列を作れます

array([False, False, False, False, False,  True], dtype=bool)

In [35]:
a[a>4]

array([5])

In [36]:
a.clip(0, 4)

array([0, 1, 2, 3, 4, 4])

## Handling non-existing values
The power of NumPy's indexing capabilities comes in handy when preprocessing data that we have just read in from a text  le. It will most likely contain invalid values, which we will mark as not being a real number using numpy.NAN as follows:

In [38]:
c = np.array([1, 2, np.NAN, 3, 4]) # let's pretend we have read this from a text file
np.isnan(c)

array([False, False,  True, False, False], dtype=bool)

In [ ]:
c[~np.isnan(c)]

## Comparing runtime behaviors